name: build and run tests

on:
  push:
    branches: [ server ]
  pull_request:
    branches: [ server ]
    
jobs:
  build:
    
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    # install dependencies
    - name: update
      run: sudo apt-get update
    - name: boost
      run: sudo apt-get install -y libboost-program-options-dev libboost-serialization-dev libboost-system-dev libboost-test-dev
#     - name: Cache boost
#       uses: actions/cache@v2
#       id: cache-boost
#       with:
#         path: "~/boost"
#         key: libboost-all-dev
#     - name: load cache
#       if: steps.cache-boost.outputs.cache-hit == 'true'
#       run: |
#         sudo cp --force --recursive ~/boost/* /
#     - name: install cache
#       if: steps.cache-boost.outputs.cache-hit != 'true'
#       run: |
#         sudo apt-get update && sudo apt-get install --yes libboost-all-dev
#         mkdir -p ~/boost
#         for dep in libboost-all-dev; do
#           dpkg -L $dep | while IFS= read -r f; do if test -f $f; then echo $f; fi; done | xargs cp --parents --target-directory ~/boost/
#         done
    - name: postgresql
      run: sudo apt-get install --yes --quiet libpq-dev postgresql-server-dev-all # postgresql  
    # build project
    - name: mkdir
      run: mkdir build
    - name: cmake build
      run: cmake -Bbuild -H.
    - name: cmake make
      run: cmake --build build/ --target all
      env:
        MAKEFLAGS: "-j2"
    # run tests
    - name: run tests
      run: build/test/Test
